In [2]:
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
import datetime

In [3]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [7]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [5]:
...
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([110])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

2022-04-01 16:39:49.682489: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[131.68784]]


In [8]:
# univariate bidirectional lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
 
# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([80, 90, 100])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[112.89339]]


In [9]:

from numpy import array
length = 5
seq = array([i/float(length) for i in range(length)])
print(seq)

[0.  0.2 0.4 0.6 0.8]


In [10]:
X = seq.reshape(5, 1, 1)
y = seq.reshape(5, 1)

In [13]:
print(X)

[[[0. ]]

 [[0.2]]

 [[0.4]]

 [[0.6]]

 [[0.8]]]


In [15]:
print(y)

[[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]]


In [ ]:
# univariate bidirectional lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
 
# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([80, 90, 100])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

In [16]:

from random import random
from numpy import array
from numpy import cumsum
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import Bidirectional
 
# create a sequence classification instance
def get_sequence(n_timesteps):
	# create a sequence of random numbers in [0,1]
	X = array([random() for _ in range(n_timesteps)])
	# calculate cut-off value to change class values
	limit = n_timesteps/4.0
	# determine the class outcome for each item in cumulative sequence
	y = array([0 if x < limit else 1 for x in cumsum(X)])
	# reshape input and output data to be suitable for LSTMs
	X = X.reshape(1, n_timesteps, 1)
	y = y.reshape(1, n_timesteps, 1)
	return X, y
 
# define problem properties
n_timesteps = 10
# define LSTM
model = Sequential()
model.add(Bidirectional(LSTM(20, return_sequences=True), input_shape=(n_timesteps, 1)))
model.add(TimeDistributed(Dense(1, activation='sigmoid')))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# train LSTM
for epoch in range(1000):
	# generate new random sequence
	X,y = get_sequence(n_timesteps)
	# fit model for one epoch on this sequence
	model.fit(X, y, epochs=1, batch_size=1, verbose=2)
# evaluate LSTM
X,y = get_sequence(n_timesteps)
yhat = model.predict_classes(X, verbose=0)
for i in range(n_timesteps):
	print('Expected:', y[0, i], 'Predicted', yhat[0, i])

1/1 - 3s - loss: 0.6874 - accuracy: 0.5000 - 3s/epoch - 3s/step
1/1 - 0s - loss: 0.6878 - accuracy: 0.4000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6840 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6805 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6817 - accuracy: 0.7000 - 7ms/epoch - 7ms/step
1/1 - 0s - loss: 0.6743 - accuracy: 0.7000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6801 - accuracy: 0.7000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6668 - accuracy: 0.9000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.6722 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.6667 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.6692 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.6627 - accuracy: 0.7000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.6639 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.6597 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.6724 - accuracy: 0.6000 - 4ms/epoch - 4ms/step
1/1 - 0s - l

1/1 - 0s - loss: 0.1795 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.2020 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1317 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.4678 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.4255 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1327 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.3030 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1781 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.3230 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1886 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1692 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1264 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1939 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1309 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1227 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s -

1/1 - 0s - loss: 0.3234 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1417 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1408 - accuracy: 1.0000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.2391 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1351 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1343 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.4292 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.3014 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1754 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1367 - accuracy: 0.9000 - 11ms/epoch - 11ms/step
1/1 - 0s - loss: 0.1191 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1838 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1166 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1256 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.3950 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s

1/1 - 0s - loss: 0.1438 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.2004 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1771 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1027 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1941 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1033 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1223 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1177 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1593 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0980 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1636 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1916 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1092 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0975 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.2163 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s -

1/1 - 0s - loss: 0.0934 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0996 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0908 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0907 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1155 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1650 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.4670 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1860 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.2444 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1561 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1176 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.2835 - accuracy: 0.8000 - 6ms/epoch - 6ms/step
1/1 - 0s - loss: 0.0859 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.2101 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0822 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s -

1/1 - 0s - loss: 0.0794 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1376 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1276 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1862 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0992 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0780 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.3406 - accuracy: 0.8000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0872 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0744 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0923 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1197 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1405 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0886 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1214 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0759 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s -

1/1 - 0s - loss: 0.1458 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0963 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0885 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1541 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.2205 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1106 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1226 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1123 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0959 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1167 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0799 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1443 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1491 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1089 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0985 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s -

1/1 - 0s - loss: 0.0742 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.0743 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.3262 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1638 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0776 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0951 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0975 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1497 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.0634 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.2258 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1998 - accuracy: 0.9000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.2801 - accuracy: 0.8000 - 5ms/epoch - 5ms/step
1/1 - 0s - loss: 0.1013 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1082 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s - loss: 0.1342 - accuracy: 0.9000 - 4ms/epoch - 4ms/step
1/1 - 0s -

AttributeError: 'Sequential' object has no attribute 'predict_classes'